import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ZelosDashboard from '@/components/Sidebar/Sidebar'
import Footer from '@/components/Footer/Footer'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body className="flex min-h-screen">
        {/* Sidebar */}
        <ZelosDashboard />

        {/* Conteúdo principal */}
        <div className="flex flex-col flex-1">
          <main className="flex-1 p-6">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  )
}
