import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from '@/components/Sidebar/Sidebar';
import Footer from '@/components/Footer/Footer';
import Header from '@/components/Header/Header';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full`}>
      <body className="min-h-screen flex flex-col">
        
        {/* Header fixo no topo */}
        <Header />

        {/* Área principal com sidebar + conteúdo */}
        <div className="flex flex-1">
          {/* Sidebar à esquerda */}
          <Sidebar />

          {/* Conteúdo principal */}
          <div className="flex flex-col flex-1">
            <main className="flex-1 p-6">
              {children}
            </main>
            <Footer />
          </div>
        </div>
        
      </body>
    </html>
  );
}
